import type { Diagnosis } from "@/db/schema";

import { getDiagnosisProvider } from "../ai";
import { PROMPT_VERSION } from "../ai/prompt";
import { assertCanWrite, type AuthContext } from "../auth/authz";
import { BadRequestError, NotFoundError } from "../http/errors";
import { validate } from "../http/validate";
import { questionnaireRepository } from "../questionnaires/questionnaire.repository";
import { visitRepository } from "../visits/visit.repository";
import { diagnosisRepository } from "./diagnosis.repository";
import { visitIdParamSchema } from "./diagnosis.schema";

/**
 * Diagnosis business logic. A diagnosis is generated by the configured AI
 * provider from the visit's questionnaire, then stored immutably (structured
 * result + original raw response). No update or delete. The service depends
 * only on the DiagnosisProvider interface, so providers can be swapped without
 * changing this layer.
 */
export const diagnosisService = {
  async createForVisit(
    ctx: AuthContext,
    visitId: string,
  ): Promise<Diagnosis> {
    assertCanWrite(ctx);
    const vId = validate(visitIdParamSchema, visitId);

    const visit = await visitRepository.findById(ctx.organizationId, vId);
    if (!visit) {
      throw new NotFoundError("Visit not found in organization");
    }

    // The diagnosis is derived solely from the questionnaire, which must exist.
    const questionnaire = await questionnaireRepository.findByVisit(
      ctx.organizationId,
      vId,
    );
    if (!questionnaire) {
      throw new BadRequestError(
        "A questionnaire must be created for this visit before a diagnosis",
      );
    }

    const provider = getDiagnosisProvider();
    const result = await provider.generateDiagnosis({
      questionnaire: {
        schemaVersion: questionnaire.schemaVersion,
        answers: questionnaire.answers,
      },
      promptVersion: PROMPT_VERSION,
    });

    return diagnosisRepository.create(ctx.organizationId, {
      visitId: vId,
      questionnaireId: questionnaire.id,
      patientId: visit.patientId,
      provider: result.provider,
      model: result.model,
      promptVersion: result.promptVersion,
      reasoning: result.reasoning,
      structuredResult: result.structuredResult as unknown as Record<
        string,
        unknown
      >,
      rawResponse: result.rawResponse,
      confidence: result.confidence,
      disclaimer: result.disclaimer,
    });
  },

  async listByVisit(
    ctx: AuthContext,
    visitId: string,
  ): Promise<Diagnosis[]> {
    const vId = validate(visitIdParamSchema, visitId);
    const visit = await visitRepository.findById(ctx.organizationId, vId);
    if (!visit) {
      throw new NotFoundError("Visit not found in organization");
    }
    return diagnosisRepository.listByVisit(ctx.organizationId, vId);
  },
};
