import { sql } from "drizzle-orm";
import {
  boolean,
  date,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  real,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

// Authentication tables are owned by Better Auth and generated by its CLI into
// ./auth-schema.ts. We import `user` here for the membership FK and re-export
// the whole auth schema so the db client and the auth adapter share one schema.
import { user } from "./auth-schema";

export * from "./auth-schema";

/**
 * Sprint 1 — complete MVP schema.
 *
 * Scope: the minimum needed to run a personalized herbal-medicine visit end to
 * end inside a multi-tenant B2B platform:
 *
 *   organization → members (staff logins) → patients → visits
 *   visit → questionnaire response → diagnosis → prescription
 *
 * Deliberately excluded (future sprints): health memory, outcomes, daily
 * checks, RAG/embeddings, inventory, billing, scheduling, CRM, analytics.
 *
 * Extensibility rules followed so those can be added without breaking changes:
 *   - Every tenant-owned row carries `organization_id` (future row-level
 *     security / per-tenant scoping needs no migration).
 *   - Free-form clinical payloads (questionnaire answers, formula items) are
 *     `jsonb`, so fields can be added without altering table structure.
 *   - Controlled vocabularies are pgEnums; new values append, existing rows
 *     stay valid.
 *   - Future tables (outcomes, daily_checks, …) reference these by id; nothing
 *     here needs to change to add them.
 */

// ── Reusable audit columns ──────────────────────────────────────────────────
const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
};

// ── Enums ───────────────────────────────────────────────────────────────────
// Note: organization member roles are stored as `text` (not a pgEnum) because
// the Better Auth organization plugin writes role strings. Allowed values
// (owner | admin | practitioner | staff) are enforced in the application layer.

export const patientSex = pgEnum("patient_sex", [
  "male",
  "female",
  "other",
  "unknown",
]);

/**
 * A patient's postal address. Stored as flexible JSON (per the schema's
 * extensibility convention) and editable by the patient via the portal.
 */
export type PatientAddress = {
  line1?: string;
  line2?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  country?: string;
};

export const visitStatus = pgEnum("visit_status", [
  "open",
  "completed",
  "cancelled",
]);

export const appointmentStatus = pgEnum("appointment_status", [
  "scheduled",
  "checked_in",
  "completed",
  "cancelled",
  "no_show",
]);

// ── Tenancy ─────────────────────────────────────────────────────────────────

/**
 * A tenant: a clinic / practice. Managed by the Better Auth organization plugin
 * (mapped to this table via a `modelName` override). `logo` and `metadata` are
 * plugin fields; `updated_at` is ours.
 */
export const organizations = pgTable("organizations", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  logo: text("logo"),
  metadata: text("metadata"),
  ...timestamps,
});

/**
 * Membership of a user in an organization, with their role. Managed by the
 * Better Auth organization plugin (mapped via `modelName`). `role` is text
 * (owner | admin | practitioner | staff, enforced in the app); `title` is ours.
 */
export const organizationMembers = pgTable(
  "organization_members",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    role: text("role").notNull().default("practitioner"),
    // Professional credential, e.g. "L.Ac.", "DAOM". Optional.
    title: text("title"),
    ...timestamps,
  },
  (t) => [
    uniqueIndex("organization_members_org_user_uq").on(
      t.organizationId,
      t.userId,
    ),
    index("organization_members_user_idx").on(t.userId),
  ],
);

/** Organization invitations (Better Auth organization plugin). */
export const invitations = pgTable(
  "invitations",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    email: text("email").notNull(),
    role: text("role"),
    status: text("status").notNull().default("pending"),
    inviterId: text("inviter_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    teamId: text("team_id"),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("invitations_org_idx").on(t.organizationId),
    index("invitations_email_idx").on(t.email),
  ],
);

/**
 * A provider's profile within an organization. Exactly one per organization
 * member (unique organization_id + user_id). The member must belong to the
 * organization.
 */
export const providerProfiles = pgTable(
  "provider_profiles",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    title: text("title"),
    specialty: text("specialty"),
    licenseNumber: text("license_number"),
    npi: text("npi"),
    avatarUrl: text("avatar_url"),
    signatureUrl: text("signature_url"),
    bio: text("bio"),
    // Weekly availability: { monday: [{ start, end }], … }. Flexible JSON so the
    // shape can evolve without a migration.
    workingHours:
      jsonb("working_hours").$type<
        Record<string, Array<{ start: string; end: string }>>
      >(),
    isActive: boolean("is_active").notNull().default(true),
    ...timestamps,
  },
  (t) => [
    uniqueIndex("provider_profiles_org_user_uq").on(
      t.organizationId,
      t.userId,
    ),
    index("provider_profiles_org_idx").on(t.organizationId),
    index("provider_profiles_user_idx").on(t.userId),
  ],
);

// ── Clinical core ───────────────────────────────────────────────────────────

/** A person receiving care at an organization (distinct from a login user). */
export const patients = pgTable(
  "patients",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    fullName: text("full_name").notNull(),
    dateOfBirth: date("date_of_birth"),
    sex: patientSex("sex").notNull().default("unknown"),
    email: text("email"),
    phone: text("phone"),
    // Structured postal address, patient-editable via the portal.
    address: jsonb("address").$type<PatientAddress>(),
    // Portal link: the Better Auth user this patient can sign in as. Nullable —
    // clinic-created patients have no linked account until claimed. NOT unique:
    // one person (user) may be a patient at several clinics, so multiple rows
    // can share a user_id. Set null if the user is deleted.
    userId: text("user_id").references(() => user.id, { onDelete: "set null" }),
    // Soft delete: null = active, non-null = deleted at that time. Clinical
    // records are never hard-deleted; queries filter on `deleted_at IS NULL`.
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    ...timestamps,
  },
  (t) => [
    index("patients_org_idx").on(t.organizationId),
    // Partial index accelerating the common "active patients in an org" query.
    index("patients_org_active_idx")
      .on(t.organizationId)
      .where(sql`${t.deletedAt} is null`),
    // Portal: resolve a signed-in user's patient record(s).
    index("patients_user_idx").on(t.userId),
  ],
);

/** One clinical encounter (consultation) belonging to exactly one patient. */
export const visits = pgTable(
  "visits",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    patientId: uuid("patient_id")
      .notNull()
      .references(() => patients.id, { onDelete: "cascade" }),
    // The practitioner (organization member) conducting the visit. Nullable so a
    // visit can be recorded before a provider is assigned; set null if the
    // member is later removed.
    providerId: uuid("provider_id").references(() => organizationMembers.id, {
      onDelete: "set null",
    }),
    // The appointment this visit was created from (via check-in), if any. At
    // most one visit per appointment (unique); set null if the appointment is
    // deleted. Visits created directly (clinical workflow) leave this null.
    appointmentId: uuid("appointment_id").references(() => appointments.id, {
      onDelete: "set null",
    }),
    status: visitStatus("status").notNull().default("open"),
    chiefComplaint: text("chief_complaint"),
    // When the encounter took place (defaults to creation time).
    visitDate: timestamp("visit_date", { withTimezone: true })
      .notNull()
      .defaultNow(),
    notes: text("notes"),
    ...timestamps,
  },
  (t) => [
    index("visits_org_idx").on(t.organizationId),
    index("visits_patient_idx").on(t.patientId),
    index("visits_provider_idx").on(t.providerId),
    // One visit per appointment (multiple NULLs allowed for direct visits).
    uniqueIndex("visits_appointment_id_uq").on(t.appointmentId),
  ],
);

/**
 * Intake questionnaire for a visit. Exactly one questionnaire per visit
 * (unique visit_id). Content is stored as generic JSON in `answers`; the
 * `schema_version` selects which versioned definition validated it, so future
 * questionnaire definitions evolve without database schema changes.
 */
export const questionnaireResponses = pgTable(
  "questionnaire_responses",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    visitId: uuid("visit_id")
      .notNull()
      .references(() => visits.id, { onDelete: "cascade" }),
    patientId: uuid("patient_id")
      .notNull()
      .references(() => patients.id, { onDelete: "cascade" }),
    // Version of the questionnaire definition this content was validated against.
    schemaVersion: integer("schema_version").notNull().default(1),
    // Flexible payload so new questions never require a migration.
    answers: jsonb("answers")
      .$type<Record<string, unknown>>()
      .notNull()
      .default(sql`'{}'::jsonb`),
    submittedAt: timestamp("submitted_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    ...timestamps,
  },
  (t) => [
    // Unique: one questionnaire per visit.
    uniqueIndex("questionnaire_responses_visit_idx").on(t.visitId),
    index("questionnaire_responses_org_idx").on(t.organizationId),
    index("questionnaire_responses_patient_idx").on(t.patientId),
  ],
);

/**
 * An AI-generated diagnosis for a visit. Immutable after creation (no
 * updated_at): each generation is a permanent record storing both the
 * structured result and the original LLM response. A visit may have multiple
 * diagnoses over time (regeneration keeps history).
 */
export const diagnoses = pgTable(
  "diagnoses",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    visitId: uuid("visit_id")
      .notNull()
      .references(() => visits.id, { onDelete: "cascade" }),
    // The questionnaire the diagnosis was derived from.
    questionnaireId: uuid("questionnaire_id").references(
      () => questionnaireResponses.id,
      { onDelete: "set null" },
    ),
    patientId: uuid("patient_id")
      .notNull()
      .references(() => patients.id, { onDelete: "cascade" }),
    // AI provenance.
    provider: text("provider").notNull(),
    model: text("model").notNull(),
    promptVersion: text("prompt_version").notNull(),
    reasoning: text("reasoning"),
    // Parsed, structured diagnosis (patterns + summary).
    structuredResult: jsonb("structured_result")
      .$type<Record<string, unknown>>()
      .notNull(),
    // The original, unmodified LLM response.
    rawResponse: jsonb("raw_response").$type<unknown>().notNull(),
    // 0..1 overall confidence, when provided by the model.
    confidence: real("confidence"),
    disclaimer: text("disclaimer").notNull(),
    // The active diagnosis for the visit. Clinical content stays immutable;
    // only this marker moves. At most one active diagnosis per visit (enforced
    // by the partial unique index below).
    isActive: boolean("is_active").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("diagnoses_visit_idx").on(t.visitId),
    index("diagnoses_org_idx").on(t.organizationId),
    index("diagnoses_patient_idx").on(t.patientId),
    index("diagnoses_questionnaire_idx").on(t.questionnaireId),
    // At most one active diagnosis per visit.
    uniqueIndex("diagnoses_active_per_visit_uq")
      .on(t.visitId)
      .where(sql`${t.isActive}`),
  ],
);

/**
 * An AI-generated herbal prescription. Immutable after creation. Belongs to
 * exactly one diagnosis and is generated from that diagnosis's structured
 * clinical assessment. Stores the structured prescription and the original LLM
 * response. A diagnosis may have multiple prescriptions over time (history).
 */
export const prescriptions = pgTable(
  "prescriptions",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    // The diagnosis this prescription treats.
    diagnosisId: uuid("diagnosis_id")
      .notNull()
      .references(() => diagnoses.id, { onDelete: "cascade" }),
    visitId: uuid("visit_id")
      .notNull()
      .references(() => visits.id, { onDelete: "cascade" }),
    patientId: uuid("patient_id")
      .notNull()
      .references(() => patients.id, { onDelete: "cascade" }),
    // AI provenance.
    provider: text("provider").notNull(),
    model: text("model").notNull(),
    promptVersion: text("prompt_version").notNull(),
    // Parsed, structured prescription (formula + herbs + instructions).
    structuredResult: jsonb("structured_result")
      .$type<Record<string, unknown>>()
      .notNull(),
    // The original, unmodified LLM response.
    rawResponse: jsonb("raw_response").$type<unknown>().notNull(),
    disclaimer: text("disclaimer").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("prescriptions_visit_idx").on(t.visitId),
    index("prescriptions_patient_idx").on(t.patientId),
    index("prescriptions_org_idx").on(t.organizationId),
    index("prescriptions_diagnosis_idx").on(t.diagnosisId),
  ],
);

/**
 * A scheduled appointment between a patient and a provider. `provider_id`
 * references a provider profile. No overlapping active appointments for the same
 * provider (enforced in the service).
 */
export const appointments = pgTable(
  "appointments",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    patientId: uuid("patient_id")
      .notNull()
      .references(() => patients.id, { onDelete: "cascade" }),
    providerId: uuid("provider_id")
      .notNull()
      .references(() => providerProfiles.id, { onDelete: "cascade" }),
    startTime: timestamp("start_time", { withTimezone: true }).notNull(),
    endTime: timestamp("end_time", { withTimezone: true }).notNull(),
    status: appointmentStatus("status").notNull().default("scheduled"),
    notes: text("notes"),
    ...timestamps,
  },
  (t) => [
    index("appointments_org_idx").on(t.organizationId),
    index("appointments_patient_idx").on(t.patientId),
    index("appointments_provider_idx").on(t.providerId),
    // Accelerates overlap checks and provider/date-range listing.
    index("appointments_provider_start_idx").on(t.providerId, t.startTime),
  ],
);

/**
 * The current SOAP note for a visit (one per visit). Section content is plain
 * text / markdown. `version` increments on each save; every save also appends an
 * immutable row to soap_note_revisions.
 */
export const soapNotes = pgTable(
  "soap_notes",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    visitId: uuid("visit_id")
      .notNull()
      .references(() => visits.id, { onDelete: "cascade" }),
    patientId: uuid("patient_id")
      .notNull()
      .references(() => patients.id, { onDelete: "cascade" }),
    subjective: text("subjective").notNull().default(""),
    objective: text("objective").notNull().default(""),
    assessment: text("assessment").notNull().default(""),
    plan: text("plan").notNull().default(""),
    version: integer("version").notNull().default(1),
    ...timestamps,
  },
  (t) => [
    uniqueIndex("soap_notes_visit_uq").on(t.visitId),
    index("soap_notes_org_idx").on(t.organizationId),
    index("soap_notes_patient_idx").on(t.patientId),
  ],
);

/** Immutable snapshot of a SOAP note at a given version (edit history). */
export const soapNoteRevisions = pgTable(
  "soap_note_revisions",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    soapNoteId: uuid("soap_note_id")
      .notNull()
      .references(() => soapNotes.id, { onDelete: "cascade" }),
    visitId: uuid("visit_id")
      .notNull()
      .references(() => visits.id, { onDelete: "cascade" }),
    version: integer("version").notNull(),
    subjective: text("subjective").notNull().default(""),
    objective: text("objective").notNull().default(""),
    assessment: text("assessment").notNull().default(""),
    plan: text("plan").notNull().default(""),
    authorId: text("author_id").references(() => user.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("soap_note_revisions_note_version_uq").on(
      t.soapNoteId,
      t.version,
    ),
    index("soap_note_revisions_note_idx").on(t.soapNoteId),
    index("soap_note_revisions_visit_idx").on(t.visitId),
    index("soap_note_revisions_org_idx").on(t.organizationId),
  ],
);

// ── Inferred types ──────────────────────────────────────────────────────────
export type Organization = typeof organizations.$inferSelect;
export type NewOrganization = typeof organizations.$inferInsert;
export type User = typeof user.$inferSelect;
export type NewUser = typeof user.$inferInsert;
export type OrganizationMember = typeof organizationMembers.$inferSelect;
export type NewOrganizationMember = typeof organizationMembers.$inferInsert;
export type Invitation = typeof invitations.$inferSelect;
export type NewInvitation = typeof invitations.$inferInsert;
export type ProviderProfile = typeof providerProfiles.$inferSelect;
export type NewProviderProfile = typeof providerProfiles.$inferInsert;
export type Appointment = typeof appointments.$inferSelect;
export type NewAppointment = typeof appointments.$inferInsert;
export type SoapNote = typeof soapNotes.$inferSelect;
export type NewSoapNote = typeof soapNotes.$inferInsert;
export type SoapNoteRevision = typeof soapNoteRevisions.$inferSelect;
export type NewSoapNoteRevision = typeof soapNoteRevisions.$inferInsert;
export type Patient = typeof patients.$inferSelect;
export type NewPatient = typeof patients.$inferInsert;
export type PatientUpdate = Partial<
  Omit<NewPatient, "id" | "organizationId" | "createdAt" | "updatedAt">
>;
export type Visit = typeof visits.$inferSelect;
export type NewVisit = typeof visits.$inferInsert;
export type QuestionnaireResponse = typeof questionnaireResponses.$inferSelect;
export type NewQuestionnaireResponse =
  typeof questionnaireResponses.$inferInsert;
export type Diagnosis = typeof diagnoses.$inferSelect;
export type NewDiagnosis = typeof diagnoses.$inferInsert;
export type Prescription = typeof prescriptions.$inferSelect;
export type NewPrescription = typeof prescriptions.$inferInsert;
